name: Upload markdown to Cloudflare R2

on:
  push:
    paths:
      - '**/*.md'
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Upload files to Cloudflare R2
        uses: ryand56/r2-upload-action@latest
        with: 
          r2-account-id: ${{ secrets.R2_ACCOUNT_ID }}
          r2-access-key-id: ${{ secrets.R2_KEY_ID }}
          r2-secret-access-key: ${{ secrets.R2_SECRET_ACCESS_KEY}}
          r2-bucket: ${{ secrets.R2_BUCKET }}
          source-dir: './lessons/*'